export const charmap = {
  "washerwoman": {
    "Name": "Washerwoman",
    "Summary":
      "You start knowing that 1 of 2 players is a particular Townsfolk.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "librarian": {
    "Name": "Librarian",
    "Summary":
      "You start knowing that 1 of 2 players is a particular Outsider. (Or that zero are in play.)",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "investigator": {
    "Name": "Investigator",
    "Summary": "You start knowing that 1 of 2 players is a particular Minion.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "chef": {
    "Name": "Chef",
    "Summary": "You start knowing how many pairs of evil players there are.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "empath": {
    "Name": "Empath",
    "Summary":
      "Each night, you learn how many of your 2 alive neighbours are evil.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "fortune_teller": {
    "Name": "Fortune Teller",
    "Summary":
      "Each night, choose 2 players: you learn if either is a Demon. There is a good player that registers as a Demon to you.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "undertaker": {
    "Name": "Undertaker",
    "Summary":
      "Each night*, you learn which character died by execution today.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "monk": {
    "Name": "Monk",
    "Summary":
      "Each night*, choose a player (not yourself): they are safe from the Demon tonight.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "slayer": {
    "Name": "Slayer",
    "Summary":
      "Once per game, during the day, publicly choose a player: if they are the Demon, they die.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": true,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "soldier": {
    "Name": "Soldier",
    "Summary": "You are safe from the Demon.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "ravenkeeper": {
    "Name": "Ravenkeeper",
    "Summary":
      "If you die at night, you are woken to choose a player: you learn their character.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "virgin": {
    "Name": "Virgin",
    "Summary":
      "The 1st time you are nominated, if the nominator is a Townsfolk, they are executed immediately.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "mayor": {
    "Name": "Mayor",
    "Summary":
      "If only 3 players live & no execution occurs, your team wins. If you die at night, another player might die instead.",
    "Type": "Townsfolk",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "butler": {
    "Name": "Butler",
    "Summary":
      "Each night, choose a player (not yourself): tomorrow, you may only vote if they are voting too.",
    "Type": "Outsider",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "saint": {
    "Name": "Saint",
    "Summary": "If you die by execution, your team loses.",
    "Type": "Outsider",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "recluse": {
    "Name": "Recluse",
    "Summary":
      "You might register as evil & as a Minion or Demon, even if dead.",
    "Type": "Outsider",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "drunk": {
    "Name": "Drunk",
    "Summary":
      "You do not know you are the Drunk. You think you are a Townsfolk character, but you are not.",
    "Type": "Outsider",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "poisoner": {
    "Name": "Poisoner",
    "Summary":
      "Each night, choose a player: they are poisoned tonight and tomorrow day.",
    "Type": "Minion",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "spy": {
    "Name": "Spy",
    "Summary":
      "Each night, you see the Grimoire. You might register as good & as a Townsfolk or Outsider, even if dead.",
    "Type": "Minion",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "baron": {
    "Name": "Baron",
    "Summary": "There are extra Outsiders in play. [+2 Outsiders]",
    "Type": "Minion",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "scarlet_woman": {
    "Name": "Scarlet Woman",
    "Summary":
      "If there are 5 or more players alive & the Demon dies, you become the Demon. (Travellers don’t count.)",
    "Type": "Minion",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "imp": {
    "Name": "Imp",
    "Summary":
      "Each night*, choose a player: they die. If you kill yourself this way, a Minion becomes the Imp.",
    "Type": "Demon",
    "Script": "Trouble Brewing",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "clockmaker": {
    "Name": "Clockmaker",
    "Summary":
      "You start knowing how many steps from the Demon to its nearest Minion.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "dreamer": {
    "Name": "Dreamer",
    "Summary":
      "Each night, choose a player (not yourself or Travellers): you learn 1 good & 1 evil character, 1 of which is correct.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "snake_charmer": {
    "Name": "Snake Charmer",
    "Summary":
      "Each night, choose an alive player: a chosen Demon swaps characters & alignments with you & is then poisoned.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "mathematician": {
    "Name": "Mathematician",
    "Summary":
      "Each night, you learn how many players’ abilities worked abnormally (since dawn) due to another character’s ability.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "flowergirl": {
    "Name": "Flowergirl",
    "Summary": "Each night*, you learn if a Demon voted today.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "town_crier": {
    "Name": "Town Crier",
    "Summary": "Each night*, you learn if a Minion nominated today.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "oracle": {
    "Name": "Oracle",
    "Summary": "Each night*, you learn how many dead players are evil.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "savant": {
    "Name": "Savant",
    "Summary":
      "Each day, you may visit the Storyteller to learn 2 things in private: 1 is true & 1 is false.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": true,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "seamstress": {
    "Name": "Seamstress",
    "Summary":
      "Once per game, at night, choose 2 players (not yourself): you learn if they are the same alignment.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "philosopher": {
    "Name": "Philosopher",
    "Summary":
      "Once per game, at night, choose a good character: gain that ability. If this character is in play, they are drunk.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "artist": {
    "Name": "Artist",
    "Summary":
      "Once per game, during the day, privately ask the Storyteller any yes/no question.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": true,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "juggler": {
    "Name": "Juggler",
    "Summary":
      "On your 1st day, publicly guess up to 5 players’ characters. That night, you learn how many you got correct.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": true,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "sage": {
    "Name": "Sage",
    "Summary": "If the Demon kills you, you learn that it is 1 of 2 players.",
    "Type": "Townsfolk",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "mutant": {
    "Name": "Mutant",
    "Summary":
      "If you are ‘mad’ about being an Outsider, you might be executed.",
    "Type": "Outsider",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "sweetheart": {
    "Name": "Sweetheart",
    "Summary": "When you die, 1 player is drunk from now on.",
    "Type": "Outsider",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "barber": {
    "Name": "Barber",
    "Summary":
      "If you died today or tonight, the Demon may choose 2 players (not another Demon) to swap characters.",
    "Type": "Outsider",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "klutz": {
    "Name": "Klutz",
    "Summary":
      "When you learn that you died, publicly choose 1 alive player: if they are evil, your team loses.",
    "Type": "Outsider",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "evil_twin": {
    "Name": "Evil Twin",
    "Summary":
      "You & an opposing player know each other. If the good player is executed, evil wins. Good can’t win if you both live.",
    "Type": "Minion",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": true,
  },
  "witch": {
    "Name": "Witch",
    "Summary":
      "Each night, choose a player: if they nominate tomorrow, they die. If just 3 players live, you lose this ability.",
    "Type": "Minion",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "cerenovus": {
    "Name": "Cerenovus",
    "Summary":
      "Each night, choose a player & a good character: they are ‘mad’ they are this character tomorrow, or might be executed.",
    "Type": "Minion",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "pit-hag": {
    "Name": "Pit-Hag",
    "Summary":
      "Each night*, choose a player & a character they become (if not in play). If a Demon is made, deaths tonight are arbitrary.",
    "Type": "Minion",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "fang_gu": {
    "Name": "Fang Gu",
    "Summary":
      "Each night*, choose a player: they die. The 1st Outsider this kills becomes an evil Fang Gu & you die instead. [+1 Outsider]",
    "Type": "Demon",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "vigormortis": {
    "Name": "Vigormortis",
    "Summary":
      "Each night*, choose a player: they die. Minions you kill keep their ability & poison 1 Townsfolk neighbor. [-1 Outsider]",
    "Type": "Demon",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "no_dashii": {
    "Name": "No Dashii",
    "Summary":
      "Each night*, choose a player: they die. Your 2 Townsfolk neighbors are poisoned.",
    "Type": "Demon",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "vortox": {
    "Name": "Vortox",
    "Summary":
      "Each night*, choose a player; they die. Townsfolk abilities yield false info. Each day, if no-one is executed, evil wins.",
    "Type": "Demon",
    "Script": "Sects & Violets",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "grandmother": {
    "Name": "Grandmother",
    "Summary":
      "You start knowing a good player & their character. If the Demon kills them, you die too.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "sailor": {
    "Name": "Sailor",
    "Summary":
      "Each night, choose an alive player: either you or they are drunk until dusk. You can’t die.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "chambermaid": {
    "Name": "Chambermaid",
    "Summary":
      "Each night, choose 2 alive players (not yourself): you learn how many woke tonight due to their ability.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "exorcist": {
    "Name": "Exorcist",
    "Summary":
      "Each night*, choose a player (different to last night): the Demon, if chosen, learns who you are then doesn’t wake tonight.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "innkeeper": {
    "Name": "Innkeeper",
    "Summary":
      "Each night*, choose 2 players: they can’t die tonight, but 1 is drunk until dusk.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "gambler": {
    "Name": "Gambler",
    "Summary":
      "Each night*, choose a player & guess their character: if you guess wrong, you die.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "gossip": {
    "Name": "Gossip",
    "Summary":
      "Each day, you may make a public statement. Tonight, if it was true, a player dies.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": true,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "courtier": {
    "Name": "Courtier",
    "Summary":
      "Once per game, at night, choose a character: they are drunk for 3 nights & 3 days.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "professor": {
    "Name": "Professor",
    "Summary":
      "Once per game, at night*, choose a dead player: if they are a Townsfolk, they are resurrected.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "minstrel": {
    "Name": "Minstrel",
    "Summary":
      "When a Minion dies by execution, all other players (except Travellers) are drunk until dusk tomorrow.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "tea_lady": {
    "Name": "Tea Lady",
    "Summary": "If both your alive neighbors are good, they can’t die.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": true,
  },
  "pacifist": {
    "Name": "Pacifist",
    "Summary": "Executed good players might not die.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": true,
  },
  "fool": {
    "Name": "Fool",
    "Summary": "The first time you die, you don’t.",
    "Type": "Townsfolk",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "goon": {
    "Name": "Goon",
    "Summary":
      "Each night, the 1st player to choose you with their ability is drunk until dusk. You become their alignment.",
    "Type": "Outsider",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "lunatic": {
    "Name": "Lunatic",
    "Summary":
      "You think you are a Demon, but you are not. The Demon knows who you are & who you choose at night.",
    "Type": "Outsider",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "tinker": {
    "Name": "Tinker",
    "Summary": "You might die at any time.",
    "Type": "Outsider",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "moonchild": {
    "Name": "Moonchild",
    "Summary":
      "When you learn that you died, publicly choose 1 alive player. Tonight, if it was a good player, they die.",
    "Type": "Outsider",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "godfather": {
    "Name": "Godfather",
    "Summary":
      "You start knowing which Outsiders are in play. If 1 died today, choose a player tonight: they die. [-1 or +1 Outsider]",
    "Type": "Minion",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "devils_advocate": {
    "Name": "Devil’s Advocate",
    "Summary":
      "Each night, choose a living player (different to last night): if executed tomorrow, they don’t die.",
    "Type": "Minion",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "assassin": {
    "Name": "Assassin",
    "Summary":
      "Once per game, at night*, choose a player: they die, even if for some reason they could not.",
    "Type": "Minion",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "mastermind": {
    "Name": "Mastermind",
    "Summary":
      "If the Demon dies by execution (ending the game), play for 1 more day. If a player is then executed, their team loses.",
    "Type": "Minion",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "zombuul": {
    "Name": "Zombuul",
    "Summary":
      "Each night*, if no-one died today, choose a player: they die. The 1st time you die, you live but register as dead.",
    "Type": "Demon",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "pukka": {
    "Name": "Pukka",
    "Summary":
      "Each night, choose a player: they are poisoned. The previously poisoned player dies then becomes healthy.",
    "Type": "Demon",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "shabaloth": {
    "Name": "Shabaloth",
    "Summary":
      "Each night*, choose 2 players: they die. A dead player you chose last night might be regurgitated.",
    "Type": "Demon",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "po": {
    "Name": "Po",
    "Summary":
      "Each night*, you may choose a player: they die. If your last choice was no-one, choose 3 players tonight.",
    "Type": "Demon",
    "Script": "Bad Moon Rising",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "alchemist": {
    "Name": "Alchemist",
    "Summary": "You have a not-in-play Minion ability.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "amnesiac": {
    "Name": "Amnesiac",
    "Summary":
      "You do not know what your ability is. Each day, privately guess what it is: you learn how accurate you are.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": true,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "atheist": {
    "Name": "Atheist",
    "Summary":
      "The Storyteller can break the game rules, and if executed, good wins, even if you are dead. [No evil characters]",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "balloonist": {
    "Name": "Balloonist",
    "Summary":
      "Each night, you learn a player of a different character type than last night. [+0 or +1 Outsider]",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "bounty_hunter": {
    "Name": "Bounty Hunter",
    "Summary":
      "You start knowing 1 evil player. If the player you know dies, you learn another evil player tonight. [1 Townsfolk is evil]",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "cannibal": {
    "Name": "Cannibal",
    "Summary":
      "You have the ability of the recently killed executee. If they are evil, you are poisoned until a good player dies by execution.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "choirboy": {
    "Name": "Choirboy",
    "Summary":
      "If the Demon kills the King, you learn which player is the Demon. [+the King]",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "cult_leader": {
    "Name": "Cult Leader",
    "Summary":
      "Each night, you become the alignment of an alive neighbour. If all good players choose to join your cult, your team wins.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "engineer": {
    "Name": "Engineer",
    "Summary":
      "Once per game, at night, choose which Minions or which Demon is in play.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "farmer": {
    "Name": "Farmer",
    "Summary": "If you die at night, an alive good player becomes a Farmer.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "fisherman": {
    "Name": "Fisherman",
    "Summary":
      "Once per game, during the day, visit the Storyteller for some advice to help your team win.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": true,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "general": {
    "Name": "General",
    "Summary":
      "Each night, you learn which alignment the Storyteller believes is winning: good, evil, or neither.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "high_priestess": {
    "Name": "High Priestess",
    "Summary":
      "Each night, learn which player the Storyteller believes you should talk to most.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "huntsman": {
    "Name": "Huntsman",
    "Summary":
      "Once per game, at night, choose a living player: the Damsel, if chosen, becomes a not-in-play Townsfolk. [+the Damsel]",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "king": {
    "Name": "King",
    "Summary":
      "Each night, if the dead equal or outnumber the living, you learn 1 alive character. The Demon knows who you are.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "knight": {
    "Name": "Knight",
    "Summary": "You start knowing 2 players that are not the Demon.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "lycanthrope": {
    "Name": "Lycanthrope",
    "Summary":
      "Each night*, choose an alive player: if good, they die, but they are the only player that can die tonight.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "magician": {
    "Name": "Magician",
    "Summary":
      "The Demon thinks you are a Minion. Minions think you are a Demon.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "nightwatchman": {
    "Name": "Nightwatchman",
    "Summary":
      "Once per game, at night, choose a player: they learn who you are.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "noble": {
    "Name": "Noble",
    "Summary": "You start knowing 3 players, 1 and only 1 of which is evil.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "pixie": {
    "Name": "Pixie",
    "Summary":
      "You start knowing 1 in-play Townsfolk. If you were mad that you were this character, you gain their ability when they die.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "poppy_grower": {
    "Name": "Poppy Grower",
    "Summary":
      "Minions & Demons do not know each other. If you die, they learn who each other are that night.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": true,
  },
  "preacher": {
    "Name": "Preacher",
    "Summary":
      "Each night, choose a player: a Minion, if chosen, learns this. All chosen Minions have no ability.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "shugenja": {
    "Name": "Shugenja",
    "Summary":
      "You start knowing if your closest evil player is clockwise or anti-clockwise. If equidistant, this info is arbitrary.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "steward": {
    "Name": "Steward",
    "Summary": "You start knowing 1 good player.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "village_idiot": {
    "Name": "Village Idiot",
    "Summary":
      "Each night, choose a player: you learn their alignment. [+0 to +2 Village Idiots. 1 of the extras is drunk]",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "acrobat": {
    "Name": "Acrobat",
    "Summary":
      "Each night*, if either good living neighbour is drunk or poisoned, you die.",
    "Type": "Outsider",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "damsel": {
    "Name": "Damsel",
    "Summary":
      "All Minions know you are in play. If a Minion publicly guesses you (once), your team loses.",
    "Type": "Outsider",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "golem": {
    "Name": "Golem",
    "Summary":
      "You may only nominate once per game. When you do, if the nominee is not the Demon, they die.",
    "Type": "Outsider",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": true,
  },
  "hatter": {
    "Name": "Hatter",
    "Summary":
      "If you died today or tonight, the Minion & Demon players may choose new Minion & Demon characters to be.",
    "Type": "Outsider",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "heretic": {
    "Name": "Heretic",
    "Summary":
      "Whoever wins, loses & whoever loses, wins, even if you are dead.",
    "Type": "Outsider",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "plague_doctor": {
    "Name": "Plague Doctor",
    "Summary": "If you die, the Storyteller gains a Minion ability.",
    "Type": "Outsider",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "politician": {
    "Name": "Politician",
    "Summary":
      "If you were the player most responsible for your team losing, you change alignment & win, even if dead.",
    "Type": "Outsider",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "puzzlemaster": {
    "Name": "Puzzlemaster",
    "Summary":
      "1 player is drunk, even if you die. If you guess (once) who it is, learn the Demon player, but guess wrong & get false info.",
    "Type": "Outsider",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": true,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "snitch": {
    "Name": "Snitch",
    "Summary": "Minions start knowing 3 not-in-play characters.",
    "Type": "Outsider",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "boomdandy": {
    "Name": "Boomdandy",
    "Summary":
      "If you are executed, all but 3 players die. 1 minute later, the player with the most players pointing at them, dies.",
    "Type": "Minion",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "fearmonger": {
    "Name": "Fearmonger",
    "Summary":
      "Each night, choose a player: if you nominate & execute them, their team loses. All players know if you choose a new player.",
    "Type": "Minion",
    "Script": "Experimental",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "goblin": {
    "Name": "Goblin",
    "Summary":
      "If you publicly claim to be the Goblin when nominated & are executed that day, your team wins.",
    "Type": "Minion",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "harpy": {
    "Name": "Harpy",
    "Summary":
      "Each night, choose 2 players: tomorrow, the 1st player is mad that the 2nd is evil, or one or both might die.",
    "Type": "Minion",
    "Script": "Experimental",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "marionette": {
    "Name": "Marionette",
    "Summary":
      "You think you are a good character, but you are not. The Demon knows who you are. [You neighbor the Demon]",
    "Type": "Minion",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "mezepheles": {
    "Name": "Mezepheles",
    "Summary":
      "You start knowing a secret word. The 1st good player to say this word becomes evil that night.",
    "Type": "Minion",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "organ_grinder": {
    "Name": "Organ Grinder",
    "Summary":
      "All players keep their eyes closed when voting & the vote tally is secret. Votes for you only count if you vote.",
    "Type": "Minion",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "psychopath": {
    "Name": "Psychopath",
    "Summary":
      "Each day, before nominations, you may publicly choose a player: they die. If executed, you only die if you lose roshambo.",
    "Type": "Minion",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": true,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "vizier": {
    "Name": "Vizier",
    "Summary":
      "All players know who you are. You can not die during the day. If good voted, you may choose to execute immediately.",
    "Type": "Minion",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "widow": {
    "Name": "Widow",
    "Summary":
      "On your first night, look at the Grimoire & choose a player: they are poisoned. 1 good player knows a Widow is in play.",
    "Type": "Minion",
    "Script": "Experimental",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "al-hadikhia": {
    "Name": "Al-Hadikhia",
    "Summary":
      "Each night*, choose 3 players (all players learn who): each silently chooses to live or die, but if all live, all die.",
    "Type": "Demon",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "kazali": {
    "Name": "Kazali",
    "Summary":
      "Each night*, choose a player: they die. [You choose which players are which Minions. -? to +? Outsiders]",
    "Type": "Demon",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "legion": {
    "Name": "Legion",
    "Summary":
      "Each night*, a player might die. Executions fail if only evil voted. You register as a Minion too. [Most players are Legion]",
    "Type": "Demon",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": true,
  },
  "leviathan": {
    "Name": "Leviathan",
    "Summary":
      "If more than 1 good player is executed, evil wins. All players know you are in play. After day 5, evil wins.",
    "Type": "Demon",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": true,
  },
  "lil_monsta": {
    "Name": "Lil’ Monsta",
    "Summary":
      "Each night, Minions choose who babysits Lil’ Monsta & ‘is the Demon’. Each night*, a player might die. [+1 Minion]",
    "Type": "Demon",
    "Script": "Experimental",
    "first night": false,
    "each night": true,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "lleech": {
    "Name": "Lleech",
    "Summary":
      "Each night*, choose a player: they die. You start by choosing an alive player: they are poisoned – you die if (& only if) they die.",
    "Type": "Demon",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "ojo": {
    "Name": "Ojo",
    "Summary":
      "Each night*, choose a character: they die. If they are not in play, the Storyteller chooses who dies.",
    "Type": "Demon",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": true,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "riot": {
    "Name": "Riot",
    "Summary":
      "Nominees die, but may nominate again immediately (on day 3, they must). After day 3, evil wins. [All Minions are Riot]",
    "Type": "Demon",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": true,
  },
  "yaggababble": {
    "Name": "Yaggababble",
    "Summary":
      "You start knowing a secret phrase. For each time you said it publicly today, a player might die.",
    "Type": "Demon",
    "Script": "Experimental",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "summoner": {
    "Name": "Summoner",
    "Summary":
      "You get 3 bluffs. On the 3rd night, choose a player: they become an evil Demon of your choice. [No Demon]",
    "Type": "Minion",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
  "banshee": {
    "Name": "Banshee",
    "Summary":
      "If the Demon kills you, all players learn this. From now on, you may nominate twice per day and vote twice per nomination.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": true,
    "passive": false,
  },
  "ogre": {
    "Name": "Ogre",
    "Summary":
      "On your 1st night, choose a player (not yourself): you become their alignment (you don’t know which) even if drunk or poisoned.",
    "Type": "Outsider",
    "Script": "Experimental",
    "first night": true,
    "each night": false,
    "each night*": false,
    "day": false,
    "once per game": false,
    "on trigger": false,
    "passive": false,
  },
  "alsaahir": {
    "Name": "Alsaahir",
    "Summary":
      "Once per day, if you publicly guess which players are Minion(s) and which are Demon(s), good wins.",
    "Type": "Townsfolk",
    "Script": "Experimental",
    "first night": false,
    "each night": false,
    "each night*": false,
    "day": true,
    "once per game": true,
    "on trigger": false,
    "passive": false,
  },
};

export const jinxes = {
  "Cannibal": {
    "Juggler":
      "If the Juggler guesses on their first day and dies by execution, tonight the living Cannibal learns how many guesses the Juggler got correct.",
  },
  "Chambermaid": {
    "Mathematician":
      "The Chambermaid learns if the Mathematician wakes tonight or not, even though the Chambermaid wakes first.",
  },
  "Lycanthrope": {
    "Gambler":
      "If the Lycanthrope is alive and the Gambler kills themself at night, no other players can die tonight.",
  },
  "Philosopher": {
    "Bounty Hunter":
      "If the Philosopher gains the Bounty Hunter ability, a Townsfolk might turn evil.",
  },
  "Butler": {
    "Cannibal":
      "If the Cannibal gains the Butler ability, the Cannibal learns this.",
  },
  "Lunatic": {
    "Mathematician":
      "The Mathematician learns if the Lunatic attacks a different player(s) than the real Demon attacked.",
  },
  "Ogre": {
    "Recluse":
      "If the Recluse registers as evil to the Ogre, the Ogre learns that they are evil.",
  },
  "Baron": {
    "Heretic": "The Baron might only add 1 Outsider, not 2.",
    "Plague Doctor":
      "If the Storyteller gains the Baron ability, up to two players become not-in-play Outsiders.",
  },
  "Boomdandy": {
    "Plague Doctor":
      "If the Plague Doctor is executed and the Storyteller would gain the Boomdandy ability, the Boomdandy ability triggers immediately.",
  },
  "Cerenovus": {
    "Goblin":
      "The Cerenovus may choose to make a player mad that they are the Goblin.",
  },
  "Evil Twin": {
    "Plague Doctor":
      "The Storyteller cannot gain the Evil Twin ability if the Plague Doctor dies.",
  },
  "Fearmonger": {
    "Plague Doctor":
      "If the Plague Doctor dies, a living Minion gains the Fearmonger ability in addition to their own ability, and learns this.",
  },
  "Goblin": {
    "Plague Doctor":
      "If the Plague Doctor dies, a living Minion gains the Goblin ability in addition to their own ability, and learns this.",
  },
  "Godfather": {
    "Heretic": "Only 1 jinxed character can be in play.",
  },
  "Marionette": {
    "Balloonist":
      "If the Marionette thinks that they are the Balloonist, +1 Outsider was added.",
    "Damsel": "The Marionette does not learn that a Damsel is in play.",
    "Huntsman":
      "If the Marionette thinks that they are the Huntsman, the Damsel was added.",
    "Lil' Monsta":
      "The Marionette neighbors a Minion, not the Demon. The Marionette is not woken to choose who takes the Lil’ Monsta token, and does not learn they are the Marionette if they have the Lil’ Monsta token.",
    "Plague Doctor":
      "If the Demon has a neighbor who is alive and a Townsfolk or Outsider when the Plague Doctor dies, that player becomes an evil Marionette. If there is already an extra evil player, this does not happen.",
    "Poppy Grower":
      "When the Poppy Grower dies, the Demon learns the Marionette but the Marionette learns nothing.",
    "Snitch":
      "The Marionette does not learn 3 not in-play characters. The Demon learns an extra 3 instead.",
  },
  "Organ Grinder": {
    "Butler":
      "If the Organ Grinder is causing eyes closed voting, the Butler may raise their hand to vote but their vote is only counted if their master voted too.",
    "Minstrel":
      "If the Minstrel makes everyone drunk, the Organ Grinder keeps their ability but the Minstrel keeps their eyes open when voting.",
    "Preacher":
      "If the Preacher removes the Organ Grinder ability, the Organ Grinder keeps their ability but the Preacher keeps their eyes open when voting.",
  },
  "Pit-Hag": {
    "Cult Leader":
      "If the Pit-Hag turns an evil player into the Cult Leader, they can’t turn good due to their own ability.",
    "Damsel":
      "If a Pit-Hag creates a Damsel, the Storyteller chooses which player it is.",
    "Goon":
      "If the Pit-Hag turns an evil player into the Goon, they can’t turn good due to their own ability.",
    "Heretic": "A Pit-Hag can not create a Heretic.",
    "Ogre":
      "If the Pit-Hag turns an evil player into the Ogre, they can’t turn good due to their own ability.",
    "Politician":
      "If the Pit-Hag turns an evil player into the Politician, they can’t turn good due to their own ability.",
    "Village Idiot":
      "If there is a spare token, the Pit-Hag can create an extra Village Idiot. If so, the drunk Village Idiot might change.",
  },
  "Scarlet Woman": {
    "Plague Doctor":
      "If the Plague Doctor dies, a living Minion gains the Scarlet Woman ability in addition to their own ability, and learns this.",
  },
  "Spy": {
    "Alchemist": "The Alchemist can not have the Spy ability.",
    "Damsel": "If the Spy is (or has been) in play, the Damsel is poisoned.",
    "Heretic": "Only 1 jinxed character can be in play.",
    "Magician":
      "When the Spy sees the Grimoire, the Demon and Magician’s character tokens are removed.",
    "Ogre": "The Spy registers as evil to the Ogre.",
    "Plague Doctor":
      "If the Plague Doctor dies, a living Minion gains the Spy ability in addition to their own ability, and learns this.",
    "Poppy Grower":
      "If the Poppy Grower is in play, the Spy does not see the Grimoire until the Poppy Grower dies.",
  },
  "Summoner": {
    "Alchemist":
      "If there is an Alchemist-Summoner in play, the game starts with a Demon in play, as normal. If the Alchemist-Summoner chooses a player, they make that player a Demon but do not change their alignment.",
    "Clockmaker":
      "If the Summoner is in play, the Clockmaker does not receive their information until a Demon is created.",
    "Courtier":
      "If the Summoner is drunk on the 3rd night, the Summoner chooses which Demon, but the Storyteller chooses which player.",
    "Engineer":
      "If the Engineer removes a Summoner from play before that Summoner uses their ability, the Summoner uses their ability immediately.",
    "Hatter":
      "The Summoner cannot create an in-play Demon. If the Summoner creates a not-in-play Demon, deaths tonight are arbitrary.",
    "Kazali":
      "The Summoner cannot create an in-play Demon. If the Summoner creates a not-in-play Demon, deaths tonight are arbitrary.",
    "Legion":
      "If the Summoner creates Legion, most players (including all evil players) become evil Legion.",
    "Marionette":
      "The Marionette neighbors the Summoner. The Summoner knows who the Marionette is.",
    "Pit-Hag":
      "The Summoner cannot create an in-play Demon. If the Summoner creates a not-in-play Demon, deaths tonight are arbitrary.",
    "Poppy Grower":
      "If the Poppy Grower is alive when the Summoner acts, the Summoner chooses which Demon, but the Storyteller chooses which player.",
    "Preacher":
      "If the Preacher chose the Summoner on or before the 3rd night, the Summoner chooses which Demon, but the Storyteller chooses which player.",
    "Pukka":
      "The Summoner may choose a player to become the Pukka on the 2nd night.",
    "Riot": "If the Summoner creates Riot, all Minions also become Riot.",
    "Zombuul":
      "If the Summoner turns a dead player into the Zombuul, the Storyteller treats that player as a Zombuul that has died once.",
  },
  "Vizier": {
    "Alsaahir":
      "If the Vizier is in play, the Alsaahir must also guess which Demon(s) are in play.",
    "Alchemist":
      "If the Alchemist has the Vizier ability, they may only choose to execute immediately if three or more players voted, regardless of those players’ alignment.",
    "Courtier":
      "If the Vizier loses their ability, they learn this. If the Vizier is executed while they have their ability, their team wins.",
    "Fearmonger":
      "The Vizier wakes with the Fearmonger, learns who they choose and cannot choose to immediately execute that player.",
    "Investigator":
      "If the Investigator learns that the Vizier is in play, the existence of the Vizier is not announced by the Storyteller.",
    "Magician":
      "If the Vizier and Magician are both in play, the Demon does not learn the Minions.",
    "Politician": "The Politician might register as evil to the Vizier.",
    "Preacher":
      "If the Vizier loses their ability, they learn this. If the Vizier is executed while they have their ability, their team wins.",
  },
  "Widow": {
    "Alchemist": "The Alchemist can not have the Widow ability.",
    "Damsel": "If the Widow is (or has been) in play, the Damsel is poisoned.",
    "Heretic": "Only 1 jinxed character can be in play.",
    "Magician":
      "When the Widow sees the Grimoire, the Demon and Magician’s character tokens are removed.",
    "Poppy Grower":
      "If the Poppy Grower is in play, the Widow does not see the Grimoire until the Poppy Grower dies.",
  },
  "Al-Hadikhia": {
    "Mastermind":
      "If the Al-Hadikhia dies by execution, and the Mastermind is alive, the Al-Hadikhia chooses 3 good players tonight: if all 3 choose to live, evil wins. Otherwise, good wins.",
    "Scarlet Woman":
      "If there are two living Al-Hadikhias, the Scarlet Woman Al-Hadikhia becomes the Scarlet Woman again.",
  },
  "Fang Gu": {
    "Scarlet Woman":
      "If the Fang Gu chooses an Outsider and dies, the Scarlet Woman does not become the Fang Gu.",
  },
  "Kazali": {
    "Bounty Hunter":
      "An evil Townsfolk is only created if the Bounty Hunter is still in play after the Kazali acts.",
    "Choirboy":
      "The Kazali can not choose the King to become a Minion if a Choirboy is in play.",
    "Goon":
      "If the Kazali chooses the Goon to become a Minion, remaining Minion choices are decided by the Storyteller.",
    "Huntsman":
      "If the Kazali chooses the Damsel to become a Minion, and a Huntsman is in play, a good player becomes the Damsel.",
    "Marionette":
      "If the Kazali chooses to create a Marionette, they must choose one of their neighbors.",
    "Soldier":
      "If the Kazali turns the Soldier into a Minion, the Soldier chooses which not-in-play Minion to become.",
  },
  "Legion": {
    "Engineer":
      "Legion and the Engineer can not both be in play at the start of the game. If the Engineer creates Legion, most players (including all evil players) become evil Legion.",
    "Hatter":
      "If the Hatter dies and Legion is in play, nothing happens. If the Hatter dies and an evil player chooses Legion, all current evil players become Legion.",
    "Minstrel":
      "If Legion died by execution today, Legion keeps their ability, but the Minstrel might learn they are Legion.",
    "Preacher":
      "If the Preacher chooses Legion, Legion keeps their ability, but the Preacher might learn they are Legion.",
  },
  "Leviathan": {
    "Banshee":
      "If Leviathan is in play, and the Banshee dies by execution, all players learn that the Banshee has died, and the Banshee gains their ability.",
    "Farmer":
      "If Leviathan is in play & a Farmer dies by execution, a good player becomes a Farmer that night.",
    "Hatter":
      "If the Hatter dies on or after day 5, the Demon cannot choose Leviathan.",
    "Innkeeper":
      "If Leviathan nominates and executes a player the Innkeeper chose, that player does not die.",
    "Mayor":
      "If Leviathan is in play & no execution occurs on day 5, good wins.",
    "Monk":
      "If Leviathan nominates and executes the player the Monk chose, that player does not die.",
    "Pit-Hag": "After day 5, the Pit-Hag cannot choose Leviathan.",
    "Ravenkeeper":
      "If Leviathan is in play & the Ravenkeeper dies by execution, they wake that night to use their ability. They are drunk if their nominator was good.",
    "Sage":
      "If Leviathan is in play & the Sage dies by execution, they wake that night to use their ability. They are drunk if their nominator was good.",
    "Soldier":
      "If Leviathan nominates and executes the Soldier, the Soldier does not die.",
  },
  "Lil' Monsta": {
    "Hatter":
      "If a Demon chooses Lil’ Monsta, they also choose a Minion to become and babysit Lil’ Monsta tonight.",
    "Magician":
      "Each night, the Magician chooses a Minion: if that Minion & Lil’ Monsta are alive, that Minion babysits Lil’ Monsta.",
    "Organ Grinder":
      "Votes for the Organ Grinder count if the Organ Grinder is babysitting Lil’ Monsta.",
    "Poppy Grower":
      "If the Poppy Grower is in play, Minions don’t wake together. They are woken one by one, until one of them chooses to take the Lil’ Monsta token.",
    "Scarlet Woman":
      "If there are 5 or more players alive and the player holding the Lil’ Monsta token dies, the Scarlet Woman is given the Lil’ Monsta token tonight.",
    "Vizier":
      "The Vizier can die by execution if they are babysitting Lil’ Monsta.",
  },
  "Lleech": {
    "Heretic":
      "If the Lleech has poisoned the Heretic then the Lleech dies, the Heretic remains poisoned.",
    "Mastermind":
      "If the Mastermind is alive and the Lleech’s host dies by execution, the Lleech lives but loses their ability.",
    "Slayer": "If the Slayer slays the Lleech’s host, the host dies.",
  },
  "Riot": {
    "Banshee":
      "If Riot nominates and kills the Banshee, all players learn that the Banshee has died, and the Banshee may nominate two players immediately.",
    "Butler": "The Butler can not nominate their master.",
    "Cannibal":
      "Players that die by nomination register as being executed to the Cannibal.",
    "Clockmaker": "Riot registers as a Minion to the Clockmaker.",
    "Damsel": "Riot registers as a Minion to the Damsel.",
    "Devil's Advocate":
      "Players that die by nomination register as being executed to the Devil’s Advocate.",
    "Engineer":
      "Riot and the Engineer can not both be in play at the start of the game. If the Engineer creates Riot, the evil players become Riot.",
    "Exorcist": "Only 1 jinxed character can be in play.",
    "Farmer":
      "If a Riot player nominates and kills a Farmer, the Farmer uses their ability tonight.",
    "Flowergirl": "Only 1 jinxed character can be in play.",
    "Golem": "If the Golem nominates Riot, the Riot player does not die.",
    "Grandmother":
      "If a Riot player nominates and kills the Grandchild, the Grandmother dies too.",
    "Hatter":
      "If the Hatter dies, Riot is in play and a Riot chooses a different Demon, a normal evil team is created from the Riot players. If the Hatter dies and the Demon chooses Riot, Minions become Riot too.",
    "Innkeeper":
      "If a Riot player nominates an Innkeeper-protected-player, the Innkeeper-protected-player does not die.",
    "Investigator": "Riot registers as a Minion to the Investigator.",
    "King":
      "If a Riot player nominates and kills the King and the Choirboy is alive, the Choirboy uses their ability tonight.",
    "Mayor":
      "If the 3rd day begins with just three players alive, the players may choose (as a group) not to nominate at all. If so (and a Mayor is alive) then the Mayor’s team wins.",
    "Minstrel": "Only 1 jinxed character can be in play.",
    "Monk":
      "If a Riot player nominates and kills the Monk-protected-player, the Monk-protected-player does not die.",
    "Pacifist":
      "Players that die by nomination register as being executed to the Pacifist.",
    "Pit-Hag":
      "If the Pit-Hag creates Riot, all evil players become Riot. If the Pit-Hag creates Riot after day 3, the game continues for one more day.",
    "Preacher": "Riot registers as a Minion to the Preacher.",
    "Ravenkeeper":
      "If a Riot player nominates and kills the Ravenkeeper, the Ravenkeeper uses their ability tonight.",
    "Sage":
      "If a Riot player nominates and kills a Sage, the Sage uses their ability tonight.",
    "Saint":
      "If a good player nominates and kills the Saint, the Saint’s team loses.",
    "Snitch":
      "If the Snitch is in play, each Riot player gets an extra 3 bluffs.",
    "Soldier":
      "If a Riot player nominates the Soldier, the Soldier does not die.",
    "Town Crier": "Riot registers as a Minion to the Town Crier.",
    "Undertaker":
      "Players that die by nomination register as being executed to the Undertaker.",
  },
  "Vortox": {
    "Banshee":
      "If the Vortox is in play and the Demon kills the Banshee, the players still learn that the Banshee has died.",
  },
  "Yaggababble": {
    "Exorcist":
      "If the Exorcist chooses the Yaggababble, the Yaggababble ability does not kill tonight.",
  },
};
